-- create items table
CREATE OR REPLACE TABLE MYLIB/ITEMS
(
 ITM_NBR INT CHECK (ITM_NBR > 0) NOT NULL,
 ITM_NAM VARCHAR(25) NOT NULL,
 ITM_MIN INT NOT NULL,
 ITM_PRC DEC(9, 2) NOT NULL,
 ITM_TYP VARCHAR(3) NOT NULL,
 ITM_UOM VARCHAR(10) NOT NULL,
 ITM_VEN INT CHECK (ITM_VEN > 0) NOT NULL
) RCDFMT RITM
  ON REPLACE PRESERVE ROWS;

-- add primary key
ALTER TABLE MYLIB/ITEMS
 ADD PRIMARY KEY(ITM_NBR) ;

-- add foreign key for vendor number
ALTER TABLE MYLIB/ITEMS
 ADD FOREIGN KEY VENDOR (ITM_VEN)
 REFERENCES VENDORS ON DELETE NO ACTION ;

-- add table label (object text description)
LABEL ON TABLE MYLIB/ITEMS IS 'Item Master Table' ;

-- add column labels
LABEL ON COLUMN MYLIB/ITEMS
(
 ITM_NBR IS 'Item Number',
 ITM_NAM IS 'Item Name',
 ITM_MIN IS 'Minimum',
 ITM_PRC IS 'Price',
 ITM_TYP IS 'Type',
 ITM_UOM IS 'UoM',
 ITM_VEN IS 'Vendor'
) ;
